### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by django23** [DrMabuse23/generator-ionic-2#12]
`npm start`

I get the following result

```
[474] ./app/main/main.scss 1.47 kB {0} [built] [1 error]
  [476] ./~/style-loader/addStyles.js 7.21 kB {0} [built]
     + 1 hidden modules

WARNING in ./~/css-loader?sourceMap!./~/resolve-url-loader!./~/autoprefixer-loader?browsers=last 2 version!./~/sass-loader?sourceMap!./app/main/main.scss
  resolve-url-loader cannot operate: source-map error
  Cannot call method 'map' of undefined

ERROR in ./~/css-loader?sourceMap!./~/resolve-url-loader!./~/autoprefixer-loader?browsers=last 2 version!./~/sass-loader?sourceMap!./app/main/main.scss
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/django/www/anio/alliance/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/home/django/www/anio/alliance/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/home/django/www/anio/alliance/node_modules/css-loader/lib/processCss.js:181:5)
    at Object.module.exports (/home/django/www/anio/alliance/node_modules/css-loader/lib/loader.js:24:2)
 @ ./app/main/main.scss 4:14-264 13:2-17:4 14:20-270
webpack: bundle is now VALID.

```

**Comment by becush** [comment]
Same.   Out of the box

**Comment by hurrtz** [comment]
I have that error, too. And also another one :)

`[156] ./~/angular2/src/facade/async.js 19.3 kB {0} [built] [1 error]`

`[474] ./app/main/main.scss 1.47 kB {0} [built] [1 error]`

```
ERROR in ./~/angular2/src/facade/async.js
Module not found: Error: Cannot resolve module 'rxjs/observable/PromiseObservable' in /Users/hurrtz/Sites/iGolem/node_modules/angular2/src/facade
 @ ./~/angular2/src/facade/async.js 12:26-70

ERROR in ./~/css-loader?sourceMap!./~/resolve-url-loader!./~/autoprefixer-loader?browsers=last 2 version!./~/sass-loader?sourceMap!./app/main/main.scss
Module build failed:
  @import "fonts/ionicons";
 ^
      Import directives may not be used within control directives or mixins.
      in /Users/hurrtz/Sites/iGolem/node_modules/ionic-framework/components.core.scss (line 25, column 3)
 @ ./app/main/main.scss 4:14-264 13:2-17:4 14:20-270
```

**Comment by cloudscape-germany** [comment]
Lots of errors, nothing working. This is a shit generator, sorry to say.

**Comment by DrMabuse23** [comment]
sorry for answer very late but  i think it is not fair using a beta and say its shit next thing is i stopped on there because ionic change very often here api but @nottinhill if you want to use the ionic cli use it and you will see the real shit.
